# permissions for end users to view snapshotpodtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: snapshot-pod
    app.kubernetes.io/managed-by: kustomize
  name: snapshotpodtask-viewer-role
rules:
- apiGroups:
  - snapshot-pod.baizeai.io
  resources:
  - snapshotpodtasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot-pod.baizeai.io
  resources:
  - snapshotpodtasks/status
  verbs:
  - get
