apiVersion: snapshot-pod.baizeai.io/v1alpha1
kind: SnapshotPod
metadata:
  labels:
    app.kubernetes.io/name: snapshot-pod
    app.kubernetes.io/managed-by: kustomize
  name: snapshotpod-sample-no-suffix
spec:
  target:
    name: test
  triggerRound: 1
  commitOptions:
    pauseContainer: false
    timeout: 3m
    message: auto save without snapped suffix
  imageSaveOptions:
    imageRefFormat: aiharbor.daocloud.io/kebe-test/{last_repository}
    # Set appendSnappedSuffix to false to disable the full suffix
    # When false, the image tag will remain unchanged
    appendSnappedSuffix: false
#    registrySecretRef: aiharbor-secret
