apiVersion: snapshot-pod.baizeai.io/v1alpha1
kind: SnapshotPodTask
metadata:
  labels:
    app.kubernetes.io/name: snapshot-pod
    app.kubernetes.io/managed-by: kustomize
  name: snapshotpodtask-sample
spec:
  # TODO(user): Add fields here
