{{- if .Values.controller.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "snapshot-pod.fullname" . }}-controller
  labels:
    {{- include "snapshot-pod.labels" . | nindent 4 }}
    {{- with .Values.controller.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: {{ .Values.controller.serviceMonitor.interval | default "15s" }}
    {{- if .Values.controller.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.controller.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    path: {{ .Values.controller.serviceMonitor.path | default "/metrics" }}
    port: {{ .Values.controller.serviceMonitor.port | default "metrics" }}
    {{- if .Values.controller.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.controller.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
  jobLabel: {{ .Values.controller.serviceMonitor.jobLabel | default "app" }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "snapshot-pod.selectorLabels" . | nindent 6 }}
{{- end }}
