{{- if .Values.runner.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapshot-pod.fullname" . }}-runner
  labels:
    {{- include "snapshot-pod.labels" . | nindent 4 }}
    {{- with .Values.runner.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.runner.service.type | default "ClusterIP" }}
  ports:
    - name: health
      port: {{ .Values.runner.service.healthPort | default 8081 }}
      protocol: TCP
      targetPort: {{ .Values.runner.service.healthTargetPort | default 8081 }}
    - name: metrics
      port: {{ .Values.runner.service.metricsPort | default 8080 }}
      protocol: TCP
      targetPort: {{ .Values.runner.service.metricsTargetPort | default 8080 }}
  selector:
    app: {{ include "snapshot-pod.fullname" . }}-runner
{{- end }}
